context:
  id: services
  sectionClassList: services
  titleConfig:
    title: Услуги и преимущества
  advantages:
    - advantage: Грузоперевозки
    - advantage: Хранение грузов
    - advantage: Международные перевозки
    - advantage: Внутрипортовое <br>экспедирование
    - advantage: Оформление процедуры <br>таможенного транзита
  sepTitle: Наша компания внесена в единый реестр таможенных перевозчиков
  services:
  - title: "Используем <br>ГЛОСАВ"
    description: "Круглосуточное слежение за передвижением вашего груза"
  - title: "Постоянная <br>мобильная связь с <br>водителями"
    description: "Наши водители всегда на связи, что позволяет нам оперативно решать возникшие вопросы и проблемы"
  - title: "Страхование <br>грузов"
    description: "По желанию заказчика мы можем застраховать перевозимый груз"
  - title: "Аккредитация в <br>портах"
    description: "Мы имеем круглосуточный доступ на следующие терминалы: ПЛП, МТПСПБ, ММПК Бронка, ПКТ, КСТП"
  - title: "Помощь с <br>погрузкой - выгрузкой (ПРР)"
    description: "Наши специалисты всегда готовы организовать погрузочно-разгрузочные работы"
